### ISSUE TITLE
Login Page: /users/sign_in

### ISSUE THREAD

**Issue by kurt-leingang** [beer-gang/beer-gang#27]
/users/sign_in

[Screenshot wireframe](https://i.gyazo.com/b904dbe022ff75294c81cebae653b499.png)

- [x] change url to /login

- [ ] ~Implement footer w/ copyright~

- [x] add and center beergang logo:
```html
<div class="text-center" style="
    margin-top: 150px;
    margin-bottom: 40px;
">
        <img src="https://i.gyazo.com/b3a912a245f2317f6da62598787db66f.png" style="
    max-width: 300px;
">
      </div>
```

- [x] replace login with bootstrap form-group
```html
<form>
  <div class="form-group">
    
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email Address" aria-describedby="emailHelp">
    
  </div>
  <div class="form-group">
    
    <input type="password" class="form-control" placeholder="Password" id="exampleInputPassword1">
  </div>
  
  <button type="submit" class="btn btn-primary btn-lg btn-block">Sign In</button>
</form>
```

**Comment by kurt-leingang** [comment]
"exampleInputEmail1" is one of many example ids we want to rename within our own convention, correct? I believe it's "user_email" currently?

**Comment by zabrador** [comment]
Header and footer coming next. Currently used "Email" instead of "Email address". Couldn't find any mainstream examples of the latter at google/fb/twitter/etc. This also uses the normal bootstrap button, instead of the large. I wanna play around a bit with how it responds on mobile before jumping to non-default versions of bootstrap components.

**Comment by kurt-leingang** [comment]
I see you have the header in there as well now! Just a heads up that the logo and login details are slightly too close together; the overlap shows [when you click the login form](https://i.gyazo.com/9b66ecdd099afb29e1b33fbe861f8228.png).

**Comment by kurt-leingang** [comment]
- [ ] Menu button should be hidden from login page

**Comment by zabrador** [comment]
> I see you have the header in there as well now! Just a heads up that the logo and login details are slightly too close together; the overlap shows when you click the login form.

Yeah that's tough, honestly we may just need to hide it altogether on mobile for now since it's so wide in its current form.

> Menu button should be hidden from login page

I would edit the original task instead of adding requirements as extra comments! Let's think this one through though. Do we also want it hid for forget password? Change password? Register?

**Comment by zabrador** [comment]
The footer is now in it's own ticket: #38.
